---
  - name: "AIX Host file management"
    #hosts: aix
    #user: ansadmin
    hosts: all
    #user: root
    strategy: debug
    gather_facts: no
    become: yes
    become_method: su

    vars:
      p_action: ""
      ip: ""
      hostname: ""
      host_file_path: "/etc/hosts"

    tasks:
    - name: "check file before"
      shell: "more {{ host_file_path }}"
      register: "output"
    - debug: var=output.stdout_lines
      
    - name: "check if ip exists"
      ansible.builtin.lineinfile:
        path: "{{ host_file_path }}"
        state: absent
        regexp: "^{{ ip | regex_escape() }}"
      check_mode: true
      changed_when: false
      register: check

    - name: "remove from /etc/hosts"
      ansible.builtin.lineinfile:
        path: "{{ host_file_path }}"
        state: absent
        regexp: "^{{ ip | regex_escape() }}"
        backup: yes
      when: 
        - p_action  == "delete"
        - check.found == 1

    - name: "add to /etc/hosts"
      ansible.builtin.lineinfile:
        path: "{{ host_file_path }}"
        state: present
        regexp: "^{{ ip | regex_escape() }}"
        line: "{{ ip }} {{ hostname }}"
        backup: yes
      when: 
        - p_action  == "add"
        - check.found == 0