---
- name: "User and group management"
  hosts: localhost
  gather_facts: yes
  vars:
    p_action: ""
    user_name: ""
    user_group: ""
    group_create: ""
  collections:
  - ibm.power_aix
  tasks:
    - name: "Gather facts"
      ansible.builtin.debug:
        var: ansible_facts['distribution']

    #UNIX PART
    - name: UNIX Part
      block:
        - name: "check if user exists"
          ansible.builtin.getent:
            database: passwd
            key: "{{ user_name }}"
          register: user_check
          ignore_errors: false
        - ansible.builtin.debug:
            var: user_check

        - name: "check if group exists"
          ansible.builtin.getent:
            database: group
            key: "{{ user_group }}"
            split: ':'
          ignore_errors: true
          register: group_check
          # when: user_check is succeeded
        - ansible.builtin.debug:
            var: group_check

        - name: "create group if group does not exist with create"
          ansible.builtin.group:
            name: "{{ user_group }}"
            state: present
          when:
            - group_check is failed
            - group_create == "yes"

        - name: "Add user to group"
          ansible.builtin.user:
            name: "{{ user_name }}"
            comment: John Doe
            groups: "{{ user_group }}"
            append: yes
          when:
            - p_action == "add"

        - name: "Remove user from group"
          ansible.builtin.user:
            name: "{{ user_name }}"
            groups: "{{ user_group }}"
            state: absent
            remove: yes
          when:
            - p_action == "remove"
      when : ansible_facts['distribution'] == "Redhat"

    - name: "AIX Part"
      block:
        - name: "check if user exists"
          shell: "lsuser {{ user_name }} && echo true || echo false"
          args:
            warn: no
          register: user_check
        - ansible.builtin.debug:
            var: user_check

        - name: "check if group exists"
          shell: "lsgroup {{ user_group }} && echo true || echo false"
          args:
            warn: no
          register: group_check
        - ansible.builtin.debug:
            var: group_check

        - name: "create group if group does not exist and permition"
          ibm.power_aix.group:
            name: "{{ user_group }}"
            state: present
          when:
            - group_check.stdout is search("false")
            - group_create == "yes"

        - name: Add a member to a group
          ibm.power_aix.group:
            state: modify
            name: "{{ user_group }}"
            user_list_action: 'add'
            user_list_type: 'members'
            users_list: "{{ user_name }}"
          when:
            - p_action == "add"

        - name: Remove a member of a group
          ibm.power_aix.group:
            state: modify
            name: "{{ user_group }}"
            user_list_action: 'remove'
            user_list_type: 'members'
            users_list: "{{ user_name }}"
          when:
            - p_action == "remove"
      when : ansible_facts['distribution'] == "AIX"
